### ISSUE TITLE
Option to remove the target from the log message

### ISSUE THREAD

**Issue by antoyo** [Drakulix/simplelog.rs#1]
Hello.
It would be nice to have an option to remove the target from the logged message, or at least having a way to change it.
Thanks.

**Comment by Drakulix** [comment]
How would you suggest to change the api to allow for configuration?
I am thinking about adding another constructor to the loggers, that initialize with a config struct and keep the new constructor, which would use a default config.

**Comment by antoyo** [comment]
What you said is an option.
Another option is to use the builder pattern, which is used by [`env_logger`](http://rust-lang-nursery.github.io/log/env_logger/struct.LogBuilder.html).

If you choose the first option (without the builder), the config struct could implement the `Default` trait for convenience when there will be more options.

**Comment by Drakulix** [comment]
I will most likely go with an optional config struct, which also will implement `Default`, because this does not break the API.

**Comment by Drakulix** [comment]
0.3.0 includes a Config parameter. Fell free to reopen, if it does not satisfy your needs.

**Comment by antoyo** [comment]
It is a bit counter-intuitive (I have to specify `Trace` instead of `Off` to turn off a value) but it does solve this issue.
Thanks for your work.

**Comment by Drakulix** [comment]
This sounds wrong. I was quite tired yesterday, I might have overlooked something there. My idea was, that `Error` enables for every variable, `Info` for `Info` and below, `Trace` for only `Trace` and `Off` means literally off.

**Comment by antoyo** [comment]
I made some more tests:
I think the only issue is that `Off` does not suppress the output.
`Trace` works fine.

**Comment by Drakulix** [comment]
Alright, that should be easily fixable. I tell you once it is resolved.

**Comment by Drakulix** [comment]
Off is ordered above Error, I assume because it means "No Filter", instead of "filter everything". I should probably break the api again and change the LogLevelFilter to Option<LogLevel>, where None would mean "not at any level". 0.4.0 is coming later today...

**Comment by Drakulix** [comment]
0.4.0 is released.

**Comment by antoyo** [comment]
The new release has a bug. I get the following error when using a `log` macro:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
```
I believe these [lines](https://github.com/Drakulix/simplelog.rs/blob/6d405dfb7a3f9e8aa1255ba090511a174520f217/src/loggers/termlog.rs#L125-L139) should have a `&&` instead of `||` or perhaps using the following:
```rust
if let Some(time) = self.config.time {
    if time <= record.level() {
        try!(write_time(&mut *term_lock));
    }
}
```
while more verbose would be even safer.

Thanks for your work.

**Comment by Drakulix** [comment]
Right that syntax is much better.

This happens when I am tired and too lazy to write more unit tests.
0.4.1 is uploaded with more tests and this error fixed. Sorry for that inconvinience.

**Comment by antoyo** [comment]
Thanks.
One more thing: I think you forgot to remove a `println!` [here](https://github.com/Drakulix/simplelog.rs/commit/da01acac99987d8f99d933c3b8d4d39ab2192889#diff-b4aea3e418ccdb71239b96952d9cddb6R139).

**Comment by Drakulix** [comment]
Thanks, done
