### ISSUE TITLE
Update to log 0.4

### ISSUE THREAD

**Issue by matklad** [Drakulix/simplelog.rs#11]
Hi! A new major version of log was released, and simple log is not compatible with it. 

I am not sure what's the proper way to update `simplelog` though: simplelog reexports `LogLevel` and `LogLevelFilter` from `log`, but these are the structures which got changed (now they are `log::Level` and `log::LevelFilter`).

**Comment by Drakulix** [comment]
Thanks for the heads-up, I will try to update simplelog in the upcoming days.

**Comment by matklad** [comment]
>Hi! A new major version of log was released, and simple log is not compatible with it.

Yeah, just to clarify, what happens is that if you application uses `log = "0.4"` and `simple_log`, then everything compiles, but log messages are silently discarded. It took me some time to figure out what's going so, I'll leave this comment here in case someone hits a similar problem.

**Comment by Drakulix** [comment]
Fixed by #15
