### ISSUE TITLE
WriteLogger error handling?

### ISSUE THREAD

**Issue by Ryder17z** [Drakulix/simplelog.rs#111]
what's the error handling like for WriteLogger?

I don't see anything for handling if the given path/file cannot be written to
(either due to permissions, (b)locking or if the path doesn't exist)

**Comment by Drakulix** [comment]
In that case you are likely not able to create a `File` anyway (or whatever it is you want to be writing to).
But if writing fails during runtime, the error is silently dropped right now (so the application won't panic).

**Comment by Ryder17z** [comment]
Alright. Thanks for the explanation.
