### ISSUE TITLE
how do i strip formattting when using WriteLogger & TermLogger in the same CombinedLogger ?

### ISSUE THREAD

**Issue by Ryder17z** [Drakulix/simplelog.rs#112]
Should be possible to set up, but I don't see how to.

**Comment by Drakulix** [comment]
What exactly do you mean with "strip formatting", would you mind to share some code and a quick example, what it is you are trying to achieve?

You can initialize `WriteLogger` and `TermLogger` with different or the same `Config` to handle formatting, before initializing a `CombinedLogger`.

**Comment by Ryder17z** [comment]
It's simple. I want to have formatting options enabled for TermLogger but
not for WriteLogger.

Currently I'm initializing both with the default config under
CombinedLogger because I can't get the config set up right for WriteLogger.

**Comment by Drakulix** [comment]
So you could instead do something *like* this:

```
let write_config = ConfigBuilder::new()
  .set_max_level(LevelFilter::Off)
  .set_time_level(LevelFilter::Off)
  .set_thread_level(LevelFilter::Off)
  .set_target_level(LevelFilter::Off)
  .set_location_level(LevelFilter::Off)
  .build();

CombinedLogger::init(
        vec![
            TermLogger::new(LevelFilter::Warn, Config::default(), TerminalMode::Mixed, ColorChoice::Auto),
            WriteLogger::new(LevelFilter::Info, write_config, File::create("my_rust_binary.log").unwrap()),
        ]
    ).unwrap();
```

That would disable all additional information, that can be written by simplelog for the WriteLogger.

**Comment by Ryder17z** [comment]
Thanks, I'll play around with that.

**Comment by Drakulix** [comment]
Feel free to re-open, if you have problems setting that up.

**Comment by Ryder17z** [comment]
I still can't find a way to strip <tag></tag>  from WriteLogger

**Comment by Ryder17z** [comment]
> Feel free to re-open, if you have problems setting that up.

Can not reopen due to repo settings.

**Comment by Drakulix** [comment]
> I still can't find a way to strip `<tag>` `</tag>` from WriteLogger

What do you mean by `<tag>`? Not sure which part of the log message you are referring to

**Comment by Ryder17z** [comment]
E. G. From the front page example:
info!("I can write <b>bold</b> text or use tags to <red>color it</>");

These tags I want to strip.

**Comment by Drakulix** [comment]
Ah, you are referring to the paris feature.
That is indeed not configurable right now and that issue is tracked here: https://github.com/Drakulix/simplelog.rs/issues/98

Pull requests are very welcome, support for implementing this feature should have landed in paris by now. :)

**Comment by Ryder17z** [comment]
Alright. I wasn't sure if it was connected or not. Thanks for the clarification
