### ISSUE TITLE
ConfigBuilder::add_filter_allow example documentation  

### ISSUE THREAD

**Issue by chris-stones** [Drakulix/simplelog.rs#120]
is this missing the scope?  `::` 
```rs
 /// For example, `add_filter_allow(format!("{}{}","tokio", "uds"))` would allow only logging from the `tokio` crates `uds` module.
```

should be the following?
```rs
 /// For example, `add_filter_allow(format!("{}::{}","tokio", "uds"))` would allow only logging from the `tokio` crates `uds` module.
```

**Comment by chris-stones** [comment]
Skimming the code, the documentation may be misleading here?  

Since commit 7648343bd71dd2a631fb063a76af63a07d6cf754, this filter now operates on target, rather than module path.

**Comment by Drakulix** [comment]
Good catch, yes the documentation seems to be outdated here, I missed that on the PR that introduced this change. Are you perhaps available to do a fixup PR?

**Comment by chris-stones** [comment]
yep, ill fling one your way later, when I'm off-the-clock.
