### ISSUE TITLE
How to update file path of the  `WriteLogger` after I call `CombinedLogger::init`?

### ISSUE THREAD

**Issue by yaoxin1995** [Drakulix/simplelog.rs#125]
After the global logger is set to `WriteLogger` with file path `/a/b`. 

Is it possible to update the file path and let the logger log message to another file `/a/c`?

**Comment by Drakulix** [comment]
This is not possible with simplelog out of the box.

You could implement your own [`SharedLogger`](https://docs.rs/simplelog/latest/simplelog/trait.SharedLogger.html), that just wraps a `WriteLogger` inside an `Arc<Mutex<_>>`. Then you could exchange the logger in there at runtime to switch logging to a different file.

**Comment by yaoxin1995** [comment]
many thanks, problem resolved
