### ISSUE TITLE
question: full time stamp?

### ISSUE THREAD

**Issue by chris-stones** [Drakulix/simplelog.rs#127]
silly question.. im sure.  

The time-stamp by default, is only the time., for exmaple - `16:10:15 [INFO] foo bar`   
would a better default be to also include the full date ?  

Perhaps im being a bit of a noob? but it wasnt immediatly obvious how to configure simplelog for the timestamp im after.
Is it possible?

**Comment by Drakulix** [comment]
Yes it is absolutely possible by using the `ConfigBuilder` and any of its [`set_time_format` functions](https://docs.rs/simplelog/latest/simplelog/struct.ConfigBuilder.html#method.set_time_format_custom).
Then initialize your logger with the `Config` created from the builder.
