### ISSUE TITLE
Question: is it safe to use `TermLogger` across threads without additional synchronisation?

### ISSUE THREAD

**Issue by cyqsimon** [Drakulix/simplelog.rs#146]
After I call `TermLogger::init` at the start of the main thread then spin up multiple worker threads, is it safe to use the usual logging macros in these threads without additional synchronisation?

In other words, is it possible for two threads to print at the same time, and instead of producing two good lines, produce two interleaved lines of garbage? (I suspect no but just want confirmation.)

And lastly, what about `SimpleLogger` and `WriteLogger`? Do they behave the same?

Thanks in advance.

**Comment by Drakulix** [comment]
Yes, all loggers you mentioned to have an internal log that prevents log messages to interleave.
That said if you initialize multiple loggers in parallel (instead of using `init` to set a single global one) you can get interleaved lines, if they write to the same file (e.g. stdout).

**Comment by cyqsimon** [comment]
That's good to know. I've got no more questions.

Thank you again for the swift response.
