### ISSUE TITLE
"termcolor" version is too restrictive

### ISSUE THREAD

**Issue by John-Nagle** [Drakulix/simplelog.rs#147]
"Simplelog" insists on termcolor "1.1". This lock-in to an old version causes version clashes with "wgpu", which wants a more modern "^1.4.1". Please fix versioning.

How about just "1"?

**Comment by kpreid** [comment]
That was already fixed in #131, but there hasn't been a release (#141).

**Comment by digama0** [comment]
ping @Drakulix , can we get a release? This is also causing build failures for me.

**Comment by Drakulix** [comment]
Should be fixed for 0.12.2, same future proofing will be applied to master at some point before an eventual 0.13 release.
