### ISSUE TITLE
Log output is not captured by tests

### ISSUE THREAD

**Issue by AlexW-GH** [Drakulix/simplelog.rs#29]
The simplelog output is not captured by tests, due to capturing only happening on LOCAL_STDOUT.
The only way I'm aware of for writing to LOCAL_STDOUT, is using print!() and println!().

I suggest adding a dedicated logger for tests, to be able to use the stdout capturing feature.
https://github.com/AlexW-GH/simplelog.rs

**Comment by Drakulix** [comment]
Added your TestLogger in the latest release.
