### ISSUE TITLE
How to prevent logging used crates?

### ISSUE THREAD

**Issue by MTRNord** [Drakulix/simplelog.rs#3]
Tokio spams my log how can I prevent that?

**Comment by Drakulix** [comment]
There is currently no way in `simplelog` to filter by crate name.

Now that `simplelog` has a `Config` struct since v0.3 this should be relatively easy to do, I will try to find some time to add that feature soon.

**Comment by MTRNord** [comment]
Cool thanks :) as tokio spams a bit on debug.

**Comment by manio** [comment]
For the reference:
In postgres crate, author implemented this via features:
https://github.com/sfackler/rust-postgres/commit/d99843ba917902079952cd8178fa300f54a32436

... maybe you can ask for tokio authors to do it as well?

In fact I am facing the same problem with rust-ini, reported here:
https://github.com/zonyitoo/rust-ini/issues/44

**Comment by repi** [comment]
Ran into this also with spammy output from cargo & http crates that I wanted to filter out but couldn't find a mechanism to do it in simplelog

**Comment by Drakulix** [comment]
I think this is addressed well enough by #36. If any use-case is not covered, please reopen.
