### ISSUE TITLE
Ability to change timezone?

### ISSUE THREAD

**Issue by evitalis** [Drakulix/simplelog.rs#32]
I might be missing it in the documentation but is there a way to set the timezone? Looks like with the default configuration it only uses UTC which is fine from a dev perspective but may throw off users.

As a side note, would it be possible to get a clear example in the documentation for overriding the default configuration and using it for the logger?

Thanks for the good work on this.

**Comment by Drakulix** [comment]
Done in 4d9de6c9b699356a8e7236c8d3b24fad94618858
