### ISSUE TITLE
Add possibility to configure via environment variables.

### ISSUE THREAD

**Issue by PieterPenninckx** [Drakulix/simplelog.rs#34]
Would you be open to the possibility to configure `simplelog` based on environment variables (like in 
https://github.com/resamplr/rsynth/blob/9787b615098e815ee84ba6842948e5ee14db90c1/examples/test_synth.rs#L165-L213)? I can prepare a pull request for that, I just wanted to check if this is something that can be in scope of this crate.

**Comment by Drakulix** [comment]
Sorry for my (really) late answer. I am not in favor of adding this directly to the simplelog codebase. I feel this adds more complexity and can be implemented by the user themselves (like you are showing).

But I would happily accept a PR with a new example showing how you may do this, if you have the time.

**Comment by PieterPenninckx** [comment]
No problem. For real-time audio programming, we will probably need to solve another problem first anyway. (How to log without memory allocation in the realtime thread, but that's definitely out of scope for simplelog.)
