### ISSUE TITLE
Should Config::offset be Option?

### ISSUE THREAD

**Issue by ajyoon** [Drakulix/simplelog.rs#38]
4d9de6c9b699356a8e7236c8d3b24fad94618858 added a field to `Config` for `offset`. Unlike all other config options, this field is not `Option`. Consequently, users are required to specify this even if they want the same UTC default provided by `Config::default()`.

This wouldn't be such a deal if it didn't mean users need to now add `chrono` to their declared dependencies in order to instantiate it (assuming I understand rust import semantics correctly...)

**Comment by ajyoon** [comment]
Suggested change at #39 if folks agree :^)

(though while making that PR I did realize I can use the spread-default-during-struct-initialization pattern, I do still think this is worthwhile to make this field consistent with all the others)

**Comment by Drakulix** [comment]
It probably should be, although I was expecting people to use the spread-Default-syntax.
I will however likely change Config to use the builder pattern to avoid things like this bumping the major version in the future.

So thank you very much for your PR, but I will handle this differently in the next days.

**Comment by ajyoon** [comment]
makes sense, thank you!
