### ISSUE TITLE
[security] volnerable transitive dependency memoffset=0.2.1 via term="0.5.1"

### ISSUE THREAD

**Issue by chenl** [Drakulix/simplelog.rs#42]
## Summary

The dependency 
```toml
term = { version = "0.5.1", optional = true }
```

brings transitively memoffset=0.2.1 that according to `cargo audit`:
```
ID:      RUSTSEC-2019-0011
Crate:   memoffset
Version: 0.2.1
Date:    2019-07-16
URL:     https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490
Title:   Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
Solution: upgrade to: >= 0.5.0
```

## How to reproduce

```sh
cargo install cargo-audit
cargo new boom
cd boom
echo 'simplelog ="*"' >> Cargo.toml
cargo fetch
cargo audit
```

**Comment by Drakulix** [comment]
Hey @chenl,
thanks for your report. On which OS are you getting this error? I cannot reproduce on Linux and wonder if this might be related to `term`'s `winapi` dependency?

**Comment by chenl** [comment]
It seems that from the report time to now, something has changed along the dependency tree, and when I ran `cargo update` it reported that:

    ...
    Removing crossbeam v0.5.0
    Removing crossbeam-channel v0.3.9
    Removing crossbeam-deque v0.6.3
    Removing crossbeam-epoch v0.6.1
    ...
    Removing memoffset v0.2.1
    ...

And now `cargo audit` exits with no errors.
