### ISSUE TITLE
TermLogError private

### ISSUE THREAD

**Issue by jxs** [Drakulix/simplelog.rs#5]
currently `TermLogError`is private, that way i cannot call init and parse the result, or convert `TermLogError`to a project specific error, and so on.
 is there a special reason for that?

**Comment by Drakulix** [comment]
No there is no reason, I simply forgot to re-export it.
Feel free to commit a PR fixing this (maybe even make the Error more descriptive) otherwise I will do so myself in the next couple of days (and am a little short on free time right now).
