### ISSUE TITLE
Select a different output fd

### ISSUE THREAD

**Issue by Veetaha** [Drakulix/simplelog.rs#62]
Hi, this crate is a perfect low-overhead logger implementation I want.
However, from my point of view, human-readable logs should go to `stderr` instead of `stdout`.
Would it be possible to add some configuration to select `stderr` or `stdout` output for the crate?
Maybe through a cargo feature or via an init function?

**Comment by Veetaha** [comment]
Oh, I think I have mistaken this project with https://github.com/borntyping/rust-simple_logger
The issue is that `simplelog.rs` unconditionally depends on `chrono`, but I would like a logger with 0 dependencies which outputs to stderr...

**Comment by Drakulix** [comment]
Well, I would certainly accept a PR, that makes chrono optional and just disables time-formatting/output, if you are interested.

Anyway, I guess the original issue is resolved. Feel free to open another one on the subject, if needed.
