### ISSUE TITLE
`TermLogger` uses hard-coded colors

### ISSUE THREAD

**Issue by JarrettBillingsley** [Drakulix/simplelog.rs#68]
I was hoping they were configurable, but: https://github.com/Drakulix/simplelog.rs/blob/195361ccb8442a2f0a8ea2e40fdce6223d0cf0fa/src/loggers/termlog.rs#L173-L179

I don't think this would be hard to add, so if you like the idea, I could make a pull request.

**Comment by Drakulix** [comment]
Yes, this could definitely be an option for simplelog's `ConfigBuilder`.

Just make sure to keep the current settings as defaults, when you make a PR.
Also please add a re-export for `termcolor::Color`, so that users do not need to add the dependency themselves.

**Comment by JarrettBillingsley** [comment]
/pull/69 :)
