### ISSUE TITLE
Update README according to current version

### ISSUE THREAD

**Issue by GregoireHENRY** [Drakulix/simplelog.rs#71]
Hello, first of all, thank you for this great crate.
Could it be possible to update the README documentation under the section "Getting Started", where it explains the dependency version? Saying that because the example in the section "Usage" does not work with v0.7.6 ;) but indeed works for the current version: 0.9.
Many thanks!
Cheers

**Comment by tjkirch** [comment]
Looks like this was fixed in v0.10.0, which includes https://github.com/Drakulix/simplelog.rs/commit/f3603e6fbfe62803554d19553d420510512e23dd?

**Comment by Drakulix** [comment]
Jup, thanks for the headsup
