### ISSUE TITLE
README on crates.io is not updated

### ISSUE THREAD

**Issue by marco-c** [Drakulix/simplelog.rs#75]
The old `TermLogger::new(LevelFilter::Warn, Config::default(), TerminalMode::Mixed),` call with three arguments is shown in the Usage section.

**Comment by tjkirch** [comment]
Looks like this may have been fixed in v0.10.1, which includes https://github.com/Drakulix/simplelog.rs/commit/dd8f9b32a8826da5f9273b1394b0574d28f67704?
