### ISSUE TITLE
Padding module name

### ISSUE THREAD

**Issue by tekjar** [Drakulix/simplelog.rs#79]
Is it possible to pad module names? Alignment is kinda screwed up (because of different module names) when I log different modules

![image](https://user-images.githubusercontent.com/6826529/132953300-24247b10-3de5-4faa-a016-5a786b831c32.png)

Sometimes I also don't need full module path. Just module name would be sufficient. Is it possible to customize this?

**Comment by Drakulix** [comment]
Padding the module name would require to know all possible module names in advance to compute the maximum length of the module string. This is currently not something log (and therefor simplelog) supports.

But parsing the module path and just logging the module name could be done. I would accept pull requests adding this feature.

**Comment by tekjar** [comment]
Isn't passing padding as user input and overflowing if a module name doesn't fit not an option? User will know what's the maximum module length and set padding accordingly

**Comment by Drakulix** [comment]
> Isn't passing padding as user input and overflowing if a module name doesn't fit not an option? User will know what's the maximum module length and set padding accordingly

That could also work, I guess, and would be conceptually very similar to the existing thread padding:
- config: https://docs.rs/simplelog/0.10.0/simplelog/struct.ConfigBuilder.html#method.set_thread_padding
- type: https://docs.rs/simplelog/0.10.0/simplelog/enum.ThreadPadding.html

But a `ModulePadding` type would use the provided `usize` as an upper bound rather then as an amount of spaces.

I would accept a PR for that proposal (or better in addition to shortening the module path) as well.

**Comment by tekjar** [comment]
Hi @Drakulix . Created a [PR](https://github.com/Drakulix/simplelog.rs/pull/85) for this

**Comment by Drakulix** [comment]
Feel free to re-open if anyone wants to extend this, but #85 added basic padding. Thanks @tekjar
